#!/usr/bin/env bash
# Wait for CI runs, download them, and commit one note of what they measured.
#
# The collection half of a queue, per the queue skill: CI runs the games and
# cannot commit (contents: read), artifacts expire in 30 days, so something
# local has to wait, download and write the numbers down. overnight4/5 and
# queue_coup_discount each carried their own copy of this; this is the one to
# reuse (and fold those into, once none of them is running).
#
# It reads what each artifact holds, whichever workflow made it:
#   gate        full-vs-base.json + full-vs-held.json -> real acceptance, games vs plan
#   drift       report.json + the drift log's reading lines
#   experiments <slug>.json + <slug>.held.json -> score, two-sided 95% CI, acceptance
#
# It never interprets and never pushes. The note is committed by explicit path.
#
# Usage: scripts/collect_ci.sh <slug> "<title>" "<context>" <run-id>...
set -uo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)
PY=${PYTHON:-$ROOT/.venv/bin/python}
REPO=JamesYouL2/struggler
SLUG=$1; TITLE=$2; CONTEXT=$3; shift 3
RUNS="$*"
RUN=logs/collect-$SLUG/$(date +%Y%m%d-%H%M%S)
mkdir -p "$RUN"
STATUS=$ROOT/$RUN/STATUS
ATTRIB='Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>'

say() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$STATUS"; }

say "collecting [$RUNS] into $SLUG"
OUT=$ROOT/$RUN/readings.txt
: > "$OUT"
for id in $RUNS; do
  waited=0
  while :; do
    st=$(gh run view "$id" -R "$REPO" --json status -q .status 2>>"$STATUS")
    [ "$st" = completed ] && break
    if [ "$waited" -ge 28800 ]; then say "  run $id still '$st' after 8h"; break; fi
    sleep 120; waited=$((waited + 120))
  done
  DL=$ROOT/logs/ci-$id
  rm -rf "$DL"
  if gh run download "$id" -R "$REPO" -D "$DL" >>"$STATUS" 2>&1; then
    say "  run $id downloaded"
  else
    say "  run $id NOT downloaded"
  fi
  {
    echo "== run $id ($(gh run view "$id" -R "$REPO" --json workflowName,headSha -q '.workflowName+" at "+.headSha[0:7]' 2>&1))"
    gh run view "$id" -R "$REPO" --json jobs -q '.jobs[]|"   job "+.name+": "+(.conclusion//.status)' 2>&1
    # gate artifacts
    for rep in $(find "$DL" -name full-vs-base.json 2>/dev/null | sort); do
      dir=$(dirname "$rep")
      echo "   -- $(echo "$dir" | sed -E 's#.*/gate-([0-9a-f]{7})[0-9a-f]*/logs.*#base \1#')"
      $PY -c "
import json
for n in ('full-vs-base', 'full-vs-held'):
    s = json.load(open(f'$dir/{n}.json'))
    g = [x for x in s['games'] if x.get('finished')]
    sm = s.get('summary', {})
    print(f'      {n}: {len(g)} finished of {sm.get(\"planned_games\", \"?\")} planned, stop_reason {sm.get(\"stop_reason\")}')"
      $PY -m struggler.bots.benchmark --accept "$dir/full-vs-base.json" "$dir/full-vs-held.json" \
        | grep -E "strength|completeness|^ACCEPTED|^REJECTED" | sed 's/^/     /'
    done
    # drift artifacts
    for log in $(find "$DL" -name 'drift-*.log' 2>/dev/null | sort); do
      echo "   -- $(basename "$log" .log)"
      grep -E "drift check: HEAD|openings:|  score |  ok: |DRIFT|SKIPPED|FAILED|STALLED|note:" "$log" | sed 's/^/     /'
    done
    # experiment artifacts
    for held in $(find "$DL" -name '*.held.json' 2>/dev/null | sort); do
      echo "   -- $(basename "$held" .held.json)"
      $PY - "${held%.held.json}.json" "$held" <<'PYEND' | sed 's/^/     /'
import json, math, statistics, sys
from struggler.bots.benchmark import seed_scores
games = [g for p in sys.argv[1:] for g in json.load(open(p))['games']]
v = list(seed_scores(games).values())
if len(v) > 1:
    m, se = statistics.fmean(v), statistics.stdev(v) / math.sqrt(len(v))
    print(f'score {m:.3f}, 95% two-sided [{m - 1.96 * se:.3f}, {m + 1.96 * se:.3f}] over {len(v)} seeds')
PYEND
      $PY -m struggler.bots.benchmark --accept "${held%.held.json}.json" "$held" \
        | grep -E "strength|completeness|^ACCEPTED|^REJECTED" | sed 's/^/     /'
    done
    echo
  } >> "$OUT" 2>&1
done

NOTE=docs/notes/claude/$(date +%F)-$SLUG.md
{
  echo "# $TITLE"
  echo
  echo "Generated by \`scripts/collect_ci.sh\` from CI runs [$RUNS]."
  echo
  echo "$CONTEXT"
  echo
  echo '```text'
  cat "$OUT"
  echo '```'
  echo
  echo "## What this does not say"
  echo
  echo "ACCEPTED means not measurably worse, never better; a drift \"ok\" means no"
  echo "measurable drift, not equal strength. Scores are the candidate's (HEAD's, or"
  echo "the arm's): above 0.500 is the candidate doing better. Nobody has read these"
  echo "numbers yet."
} > "$NOTE"
git add -- "$NOTE" && git commit -q -m "docs: $TITLE, collected from CI" -m "$ATTRIB" -- "$NOTE" \
  && say "  committed: $(git log --oneline -1)"
say "finished"
