#!/usr/bin/env bash
# Collects the 2026-09-12 ablation arms from CI (.github/workflows/experiments.yml,
# dispatched inline, one run per arm) into one committed note.
#
# Waits for overnight4 rather than being folded into it: overnight4 was already
# running when the arms were dispatched, and bash reads a running script
# incrementally, so editing it was not an option.
#
# Collection only: it plays no games and changes no code, so it runs no suite.
# It commits one note, by explicit path. It does not interpret: a score here
# is not a verdict on whether any weight should change.
#
# Usage: scripts/overnight5.sh <arm-dir> <run-id>...
#   arm-dir holds <slug>.arm.json, the exact inline JSON each run was given.
set -uo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)
PY=${PYTHON:-$ROOT/.venv/bin/python}
RUN=logs/overnight5/$(date +%Y%m%d-%H%M%S)
mkdir -p "$RUN"
STATUS=$ROOT/$RUN/STATUS
ATTRIB='Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>'
REPO=JamesYouL2/struggler
ARMS=$1; shift
RUNS="$*"

say() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$STATUS"; }

exec 9>"$ROOT/logs/overnight5.lock"
if ! flock -n 9; then echo "overnight5 is already running" >&2; exit 5; fi

say "overnight5 queued for runs [$RUNS]; waiting for overnight4"
while $PY scripts/gate_running.py --match overnight4.sh --any-interpreter --quiet; do sleep 120; done

OUT=$ROOT/$RUN/ablations.txt
: > "$OUT"
for id in $RUNS; do
  waited=0
  while :; do
    st=$(gh run view "$id" -R "$REPO" --json status -q .status 2>>"$STATUS")
    [ "$st" = completed ] && break
    if [ "$waited" -ge 25200 ]; then say "  run $id still '$st' after 7h"; break; fi
    sleep 120; waited=$((waited + 120))
  done
  DL=$ROOT/logs/ci-$id
  if [ "$st" = completed ] && gh run download "$id" -R "$REPO" -D "$DL" >>"$STATUS" 2>&1; then
    say "  run $id downloaded"
  else
    say "  run $id NOT collected; by hand: gh run download $id -R $REPO"
    echo "-- run $id: not collected (status ${st:-unknown})" >> "$OUT"
    continue
  fi
  for rep in "$DL"/experiment-*/*.held.json; do
    [ -e "$rep" ] || continue
    dir=$(dirname "$rep"); slug=$(basename "$rep" .held.json)
    {
      echo
      echo "-- $slug (run $id, $(gh run view "$id" -R "$REPO" --json conclusion -q .conclusion))"
      $PY - "$ARMS/$slug.arm.json" "$dir/$slug.json" "$dir/$slug.held.json" <<'PYEND'
import json, sys
arm = json.load(open(sys.argv[1]))
print(f"   {arm['title']}: {json.dumps(arm['weights'])}")
print(f"   seeds {arm['seeds']} + held {arm['held']}")
for path in sys.argv[2:]:
    games = [g for g in json.load(open(path))['games'] if g.get('finished')]
    # 128 seeds x 2 seats per sample. Fewer is either --decide curtailing or a
    # stall, and the report cannot tell which (audit F4) -- so say the number.
    print(f"   {path.rsplit('/', 1)[1]}: {len(games)} of 256 planned games finished")
PYEND
      $PY -m struggler.bots.benchmark --accept "$dir/$slug.json" "$dir/$slug.held.json" \
        | grep -E "strength|^ACCEPTED|^REJECTED|nuclear losses:" | sed 's/^/   /'
    } >> "$OUT" 2>&1
  done
done

NOTE=docs/notes/claude/$(date +%F)-ablations-on-ci.md
{
  echo "# Seven ablations, one CI runner each"
  echo
  echo "Generated by \`scripts/overnight5.sh\` from \`.github/workflows/experiments.yml\` runs"
  echo "[$RUNS], dispatched 2026-09-12 against \`b721744\`. Each arm changes the named"
  echo "weights and nothing else, and plays the shipped bot over the same 128 + 128"
  echo "seeds (9400-9527, held 9528-9655), so arms are comparable with each other as"
  echo "well as with the shipped weights. Every arm was loaded through"
  echo "\`StrategicWeights.load\` before dispatch and checked to change exactly its"
  echo "fields, so none is a retired field comparing the bot with itself (shape 3)."
  echo
  echo "Why each arm, as dispatched:"
  echo
  for f in "$ARMS"/*.arm.json; do
    $PY -c "import json,sys; a=json.load(open(sys.argv[1])); print(f\"- **{a['slug']}** -- {a['context']}\")" "$f"
  done
  echo
  echo "## What was measured"
  echo
  printf '```text\n'; cat "$OUT"; printf '```\n'
  echo
  echo "## What this does not say"
  echo
  echo "The score is the ARM's, against the shipped weights: above 0.500 means the"
  echo "ablated bot did better. ACCEPTED means the ablated weights are not"
  echo "measurably worse, never that the term is useless -- at these sizes most"
  echo "real effects are unresolved, and several arms touch few decisions. A"
  echo "single-weight result is also exactly the half-change the battleground"
  echo "revamp plan warns against shipping. Nobody has read these numbers yet."
} > "$NOTE"
git add -- "$NOTE" && git commit -q -m "docs: collect seven ablation arms from CI" -m "$ATTRIB" -- "$NOTE" \
  && say "  committed: $(git log --oneline -1)"
say "overnight5 finished"
