#!/usr/bin/env bash
# Follow-on to scripts/overnight3.sh, 2026-09-12. Waits for it, then:
#
#   1. suite            -- the F1 fix landed after overnight3's suite ran
#   2. conversion       -- reach -> control and retention at horizons 1 and 2,
#                          over 192 seeds, with the F1-fixed collector
#   3. collect CI       -- the gate ladder, the decide=0 gate and the drift
#                          run: wait, download, one committed note of numbers
#
# Local by the queue skill's rule for 2 (no workflow; it plays games but
# measures the calibration, not strength) and 3 (collection is always local:
# the workflows cannot commit and artifacts expire in 30 days).
#
# Nothing depends on an earlier verdict: 2 reads games it plays, 3 reads
# what CI produced. NOT `set -e`. Explicit-path commits. Step 2 plays from a
# worktree of the launch commit.
#
# The helpers below repeat overnight3.sh's three-line say/commit/fence rather
# than move them into scripts/lib while overnight3 is running: bash reads a
# running script incrementally, and a shared file is the kind of edit that
# rule exists for. Fold them into scripts/lib/queue_common.sh afterwards.
#
# Usage: scripts/overnight4.sh "<gate run ids>" <drift run id>
set -uo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)
PY=${PYTHON:-$ROOT/.venv/bin/python}
RUN=logs/overnight4/$(date +%Y%m%d-%H%M%S)
mkdir -p "$RUN"
STATUS=$ROOT/$RUN/STATUS
ATTRIB='Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>'
NOTES=docs/notes/claude
REPO=JamesYouL2/struggler
GATE_RUNS=${1:-}
DRIFT_RUN=${2:-}
CONV_SEEDS=4000-4191

say() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$STATUS"; }
commit() {  # commit <message> <paths...>
  local msg=$1; shift
  git add -- "$@" 2>>"$STATUS"
  if git diff --cached --quiet; then say "  (nothing to commit)"; return 0; fi
  git commit -q -m "$msg" -m "$ATTRIB" -- "$@" && say "  committed: $(git log --oneline -1)"
}
fence() { printf '```text\n'; cat "$1" 2>/dev/null || echo "(missing: $1)"; printf '```\n'; }

exec 9>"$ROOT/logs/overnight4.lock"
if ! flock -n 9; then echo "overnight4 is already running" >&2; exit 5; fi

say "overnight4 queued; waiting for overnight3"
while $PY scripts/gate_running.py --match overnight3.sh --any-interpreter --quiet; do sleep 120; done
LAUNCH=$(git rev-parse HEAD)
say "starting at ${LAUNCH:0:7}; logs in $RUN"

# --- 1. suite --------------------------------------------------------------
say "step 1: full test suite"
if $PY -m pytest -q -p no:cacheprovider > "$RUN/suite.log" 2>&1; then
  say "  suite PASSED: $(tail -1 "$RUN/suite.log")"
else
  say "  suite FAILED -- committing nothing and stopping."
  grep -E '^(FAILED|ERROR)' "$RUN/suite.log" | head -5 | tee -a "$STATUS"
  exit 1
fi

# --- 2. conversion and retention, F1-fixed, two horizons -------------------
say "step 2: conversion at horizons 1,2 over $CONV_SEEDS"
WT=$(mktemp -d)
trap 'git -C "$ROOT" worktree remove --force "$WT" 2>/dev/null' EXIT
if git worktree add -q --detach "$WT" "$LAUNCH" \
   && (cd "$WT" && PYTHONPATH="$WT/src" $PY scripts/measure_access_conversion.py \
         --seeds "$CONV_SEEDS" --horizons 1,2 --workers 8) \
         > "$RUN/conversion.txt" 2> "$RUN/conversion.err"; then
  say "  done"
else
  say "  FAILED -- see $RUN/conversion.err"; tail -5 "$RUN/conversion.err" | tee -a "$STATUS"
fi
NOTE2=$NOTES/$(date +%F)-conversion-and-retention-after-f1.md
{
  echo "# Reach -> control and retention, re-measured with the F1 fix, at two horizons"
  echo
  echo "Generated by \`scripts/overnight4.sh\` step 2 at \`${LAUNCH:0:7}\`. Codex's audit F1:"
  echo "the collector resolved an opportunity when a scoring card was *chosen*, not"
  echo "when its region scored, and Final Scoring resolved nothing. The table in"
  echo "\`2026-09-13-handoff-for-codex.md\` section 2 (96 seeds, before \`7a1ac6c\`) and"
  echo "\`CONVERSION_P\` both come from that collector. This is the same measurement"
  echo "with resolution inside the engine's scoring, over $CONV_SEEDS, at horizon 1"
  echo "(the next scoring of the region) and horizon 2 (the one after) -- the"
  echo "question in section 4d of that handoff. Final Scoring now resolves, so"
  echo "censoring is lower than before and is printed per table."
  echo
  fence "$RUN/conversion.txt"
  echo
  echo "## What this does not say"
  echo
  echo "Not a strength measurement. The bot that played these games is the"
  echo "shipped one, whose access pricing came from the biased figures, so this"
  echo "measures that bot's games and not an unconditioned conversion rate. The"
  echo "audit also notes opportunities within a game are correlated, so the"
  echo "binomial intervals understate the uncertainty. Horizon 2 is censored"
  echo "hardest in games that end early. Nobody has read these numbers yet."
} > "$NOTE2"
commit "docs: reach -> control and retention with the F1-fixed collector, at two horizons" "$NOTE2"

# --- 3. collect the CI runs --------------------------------------------------
say "step 3: collecting CI runs: gates [$GATE_RUNS], drift [$DRIFT_RUN]"
wait_run() {  # wait_run <id>: returns once completed, or after 7h
  local waited=0 st
  while :; do
    st=$(gh run view "$1" -R "$REPO" --json status -q .status 2>>"$STATUS")
    [ "$st" = completed ] && return 0
    [ "$waited" -ge 25200 ] && { say "  run $1 still '$st' after 7h"; return 1; }
    sleep 120; waited=$((waited + 120))
  done
}
OUT3=$ROOT/$RUN/ci-summary.txt
: > "$OUT3"
for id in $GATE_RUNS $DRIFT_RUN; do
  if wait_run "$id" && gh run download "$id" -R "$REPO" -D "$ROOT/logs/ci-$id" >>"$STATUS" 2>&1; then
    say "  run $id downloaded"
  else
    say "  run $id NOT collected; by hand: gh run download $id -R $REPO"
  fi
  gh run view "$id" -R "$REPO" --json jobs -q '.jobs[]|"  job "+.name+": "+(.conclusion//.status)' >> "$OUT3" 2>&1
done
{
  echo
  echo "== gates: HEAD against each base, every game played (decide=0), seeds 4000-4063 + held 5000-5063"
  for id in $GATE_RUNS; do
    for rep in "$ROOT"/logs/ci-$id/gate-*/logs/game-check/gate-*/full-vs-base.json; do
      [ -e "$rep" ] || continue
      dir=$(dirname "$rep")
      base=$(basename "$(dirname "$(dirname "$(dirname "$dir")")")"); base=${base#gate-}
      echo
      echo "-- base ${base:0:7}: $(git log -1 --format=%s "$base" 2>/dev/null) (run $id)"
      $PY -c "
import json, sys
for n in ('full-vs-base', 'full-vs-held'):
    g = [x for x in json.load(open(f'$dir/{n}.json'))['games'] if x.get('finished')]
    print(f'   {n}: {len(g)} of 128 planned games finished' + ('' if len(g) == 128 else '  <-- INCOMPLETE (audit F4)'))"
      $PY -m struggler.bots.benchmark --accept "$dir/full-vs-base.json" "$dir/full-vs-held.json" \
        | grep -E "strength|^ACCEPTED|^REJECTED|nuclear losses:" | sed 's/^/   /'
    done
  done
  echo
  echo "== drift: HEAD against each anchor"
  for log in "$ROOT"/logs/ci-$DRIFT_RUN/drift-*/drift-*.log; do
    [ -e "$log" ] || continue
    echo
    echo "-- $(basename "$log" .log)"
    tail -25 "$log" | sed 's/^/   /'
  done
} >> "$OUT3" 2>&1
NOTE3=$NOTES/$(date +%F)-gate-ladder-since-05b6690.md
{
  echo "# HEAD gated against every major behaviour commit since \`05b6690\`, from CI"
  echo
  echo "Generated by \`scripts/overnight4.sh\` step 3. \`05b6690\` is the strongest"
  echo "measured revision (\`2026-09-12-the-reshuffle-fix-cost-eight-points.md\`), and"
  echo "the last drift reading, at \`347447c\`, called HEAD worse than it. Four behaviour"
  echo "changes landed after that reading. Each gate here plays the same HEAD"
  echo "(\`b721744\`, bots identical to \`93a78d3\`) against one base on the same 128+128"
  echo "seeds with early stopping off, so the readings share seeds and differ only in"
  echo "the base. Reading adjacent rungs as the step between them is a subtraction"
  echo "of two scores each about +/-0.03, so a step under about five points is not"
  echo "resolved by this ladder."
  echo
  fence "$OUT3"
  echo
  echo "## What this does not say"
  echo
  echo "ACCEPTED means HEAD is not measurably worse than that base, never better."
  echo "A rung is not an attribution: the bases differ from each other by several"
  echo "commits, and interactions between them are not separated. Runner wall-clock"
  echo "is not quotable. Nobody has read these numbers yet."
} > "$NOTE3"
commit "docs: collect the gate ladder since 05b6690 and the drift run from CI" "$NOTE3"

say "overnight4 finished"
grep -E "PASSED|FAILED|done|collected|downloaded|committed" "$STATUS" | sed 's/^/  /'
