#!/usr/bin/env bash
# Queue: P(control at scoring) for the battleground formula, measured and fitted.
#
# The maintainer, 2026-09-13: battleground value is
#   value of scoring x flip ability ** turns x P(scoring) x (a / Ops for you + b / Ops for them)
# with the constants to fit, the division probably not surviving, and
# overprotection moving the odds of control. This measures P(control at the
# region's next scoring, and the one after) with those features, fits every
# candidate shape on even seeds and scores it on odd ones, and commits one
# generated note of the raw output.
#
# Per the queue skill: no `set -e`, nothing interprets, the note is committed
# by explicit path, nothing is pushed. The rows stay in logs/ (gitignored).
#
# Usage: scripts/queue_control_odds.sh            (SEEDS, WORKERS override)
set -uo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)
PY=${PYTHON:-$ROOT/.venv/bin/python}
SEEDS=${SEEDS:-7000-7191}
WORKERS=${WORKERS:-6}
RUN=logs/control-odds/$(date +%Y%m%d-%H%M%S)
mkdir -p "$RUN"
STATUS=$ROOT/$RUN/STATUS
ATTRIB='Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>'

say() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$STATUS"; }

say "measuring seeds $SEEDS with $WORKERS workers into $RUN"
if ! "$PY" scripts/measure_control_odds.py --seeds "$SEEDS" --horizons 1,2 --workers "$WORKERS" \
       --out "$RUN/rows.jsonl.gz" > "$RUN/measure.txt" 2> "$RUN/measure.err"; then
  say "measurement FAILED (see $RUN/measure.err); nothing to fit, nothing committed"
  exit 3
fi
say "measured"

for h in 1 2; do
  if "$PY" scripts/fit_control_odds.py "$RUN/rows.jsonl.gz" --horizon "$h" \
       --out "$RUN/fit-h$h.json" > "$RUN/fit-h$h.txt" 2>> "$STATUS"; then
    say "fitted horizon $h"
  else
    say "fit at horizon $h FAILED"
    echo "(fit failed; see $RUN/STATUS)" > "$RUN/fit-h$h.txt"
  fi
done

NOTES_DIR=${NOTES_DIR:-docs/notes/claude}
NOTE=$NOTES_DIR/$(date +%Y-%m-%d)-control-odds-fits.md
{
  echo "# P(control at scoring): measured, and every candidate shape fitted"
  echo
  echo "Generated by \`scripts/queue_control_odds.sh\` from \`$RUN\` (rows gitignored), seeds $SEEDS, at $(git rev-parse --short HEAD)."
  echo
  echo "The maintainer's formula, 2026-09-13: value of scoring x flip ability ** turns x P(scoring) x (a / Ops for you to control + b / Ops for them to control), with the constants to fit, the division in doubt, and overprotection moving the odds. Flip ability and the two Ops counts both describe whether the country is ours when it scores, so this measures that probability and fits shapes to it: a (controller, stability) table, reciprocal (1/(1+c)), contest share (log-cost difference), exponential (exp(-c/lambda)) and linear, each with and without overprotection. Fitted on even seeds, scored on odd seeds; battlegrounds only."
  echo
  echo "## Measured"
  echo
  echo '```'
  cat "$RUN/measure.txt"
  echo '```'
  for h in 1 2; do
    echo
    echo "## Fits, horizon $h"
    echo
    echo '```'
    cat "$RUN/fit-h$h.txt"
    echo '```'
  done
  echo
  echo "## What this does not say"
  echo
  echo "Which shape fits P(control at scoring) best on held-out seeds, and nothing else. Not what the value formula should be, not whether pricing it that way makes the bot stronger -- that is a gate -- and rows from one game are correlated, so read small log-loss differences with care. Nothing here is wired into the bot."
} > "$NOTE"

"$PY" "$ROOT/scripts/index_note.py" "$NOTE" --generated
git add "$NOTE" "$NOTES_DIR/README.md" && git commit -q -m "docs: P(control at scoring) measured and fitted, generated

$ATTRIB" -- "$NOTE" "$NOTES_DIR/README.md" && say "committed $NOTE" || say "commit FAILED for $NOTE"
say "done"
