#!/usr/bin/env bash
# HEAD against six strategic bots from before the package split, 2026-09-13.
#
# The maintainer's question: are there more regressions, and is there anything
# useful before v0.1.0? The drift canary cannot reach past the split
# (136a8c6, 09-10 07:07), so these run through scripts/legacy_anchor.py, which
# loads each old bot from its own namespace instead of through
# benchmark.load_module. Anchors bracket the features removed early on:
#
#   95b44b7  09-08 16:22  an early strategic bot
#   50e8bff  09-08 19:13  last with the Southeast Asia tier, leverage, reserve and event weights
#   1a03954  09-08 20:37  after those removals: region margin, control 1.5
#   6ec71d4  09-08 22:03  VP priced in Ops by era
#   b375ae5  09-09 18:14  the end of Codex's audit fixes
#   372609e  09-10 03:56  Military Ops in VP; the last commit before the split
#
# Local and serial per the queue skill -- CI dispatch was returning 500/502
# when this was written -- one anchor at a time, from a worktree pinned at
# launch, committing the note after every anchor. Seeds 6000-6127, the drift
# canary's, so the readings sit beside v0.1.0 (0.551), v0.2.0 (0.467),
# v0.2.1 (0.496) and 05b6690 (0.486). NOT `set -e`: an anchor that fails to
# load is recorded and the queue moves on. Nothing depends on an earlier
# verdict.
set -uo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)
PY=${PYTHON:-$ROOT/.venv/bin/python}
RUN=logs/legacy-drift/$(date +%Y%m%d-%H%M%S)
mkdir -p "$RUN"
STATUS=$ROOT/$RUN/STATUS
ATTRIB='Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>'
ANCHORS="95b44b7 50e8bff 1a03954 6ec71d4 b375ae5 372609e"
SEEDS=6000-6127
LAUNCH=$(git rev-parse HEAD)
NOTE=docs/notes/claude/$(date +%F)-drift-before-the-package-split.md

say() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$STATUS"; }

exec 9>"$ROOT/logs/legacy-drift.lock"
if ! flock -n 9; then echo "already running" >&2; exit 5; fi

WT=$(mktemp -d)
trap 'git -C "$ROOT" worktree remove --force "$WT" 2>/dev/null' EXIT
git worktree add -q --detach "$WT" "$LAUNCH" || { say "worktree FAILED"; exit 1; }
say "launch ${LAUNCH:0:7}; anchors $ANCHORS; seeds $SEEDS; logs in $RUN"

READINGS=$ROOT/$RUN/readings.txt
: > "$READINGS"
write_note() {
  {
    echo "# HEAD against the strategic bot before the package split"
    echo
    echo "Generated by \`scripts/queue_legacy_drift.sh\`, candidate \`${LAUNCH:0:7}\`, seeds $SEEDS."
    echo "Each anchor is a revision from before \`136a8c6\` (2026-09-10 07:07), loaded from"
    echo "its own namespace by \`scripts/legacy_anchor.py\` because the gate's loader cannot"
    echo "reach it. The score is HEAD's: above 0.500 is HEAD doing better, and a one-sided"
    echo "upper bound below 0.500 would mean the anchor is measurably stronger -- a"
    echo "regression somewhere between it and HEAD."
    echo
    echo "For comparison on the same seeds (drift canary): HEAD scored 0.551 vs v0.1.0,"
    echo "0.467 vs v0.2.0, 0.496 vs v0.2.1, 0.486 vs 05b6690."
    echo
    echo '```text'
    cat "$READINGS"
    echo '```'
    echo
    echo "## What this does not say"
    echo
    echo "Every anchor predates the opening books, so HEAD opens with iran/austria and"
    echo "the anchor with its own default: the two arms do not start from the same"
    echo "board, which a drift reading between post-book revisions does not suffer."
    echo "The old bots also run on today's engine, which has had rules fixed since they"
    echo "were written. A reading here is strength against HEAD under those conditions,"
    echo "not what the anchor was worth in its own day. Nobody has read these numbers yet."
  } > "$NOTE"
}

for rev in $ANCHORS; do
  say "anchor $rev: $(git log -1 --format='%ad %s' --date=format:%m-%d.%H:%M "$rev" | cut -c1-80)"
  (cd "$WT" && PYTHONPATH="$WT/src" "$PY" scripts/legacy_anchor.py "$rev" --seeds "$SEEDS" \
      --workers 8 --out "$ROOT/$RUN") >> "$READINGS" 2>>"$STATUS"
  rc=$?
  if [ "$rc" = 0 ]; then
    say "  done: $(tail -4 "$READINGS" | head -1 | cut -c1-120)"
  else
    # 6 is a stall (partial report, reading still printed); anything else a failure.
    say "  anchor $rev exit $rc -- recorded, moving on"
    echo "$rev: exit $rc (6 = stalled, partial reading above; otherwise see $RUN/legacy_*.err)" >> "$READINGS"
  fi
  echo >> "$READINGS"
  write_note
  git add -- "$NOTE" && git commit -q -m "docs: HEAD against pre-split anchor $rev" -m "$ATTRIB" -- "$NOTE" \
    && say "  committed: $(git log --oneline -1)"
done
say "finished"
