#!/usr/bin/env python
"""Turn a benchmark report into a short factual note.

The overnight runner commits after every work item, and `logs/` is
gitignored (reports are ~500KB), so what gets committed is this: the
numbers, not the raw JSON. Deliberately factual -- it states what was
measured and never what it means, because a script cannot tell the
difference between a real effect and a null result dressed as one.

    python scripts/report_note.py <report.json> --title T --slug S --context "..."
"""
from __future__ import annotations

import argparse
import datetime
import json
import pathlib


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument('report')
    ap.add_argument('--title', required=True)
    ap.add_argument('--slug', required=True)
    ap.add_argument('--context', default='')
    ap.add_argument('--out-dir', default='docs/notes/claude')
    a = ap.parse_args(argv)

    data = json.loads(pathlib.Path(a.report).read_text())
    s = data.get('summary', data)
    score = s.get('score')
    half = s.get('score_halfwidth')
    today = datetime.date.today().isoformat()

    lines = [f'# {a.title}', '']
    if a.context:
        lines += [a.context, '']
    lines += ['## What was measured', '']
    if score is not None and half is not None:
        upper = score + half
        lines += [
            f'- **score {score:.3f} +/-{half:.3f}** over {s.get("seeds")} seeds '
            f'({s.get("games")} games)',
            f'- one-sided 95% upper bound **{upper:.3f}** (acceptance needs 0.500)',
            f'- **{"reaches" if upper >= 0.500 else "does NOT reach"} parity** '
            f'on the gate\'s own rule',
        ]
        if score - half <= 0.500 <= upper:
            lines += ['- the interval straddles 0.500: this is **not a measurable '
                      'difference in either direction**, which is a bound on the '
                      'effect, not evidence that it is zero']
    for key, label in (('nuclear_losses', 'nuclear losses'),
                       ('us_win_rate', 'US win rate'),
                       ('mean_end_turn', 'mean ending turn'),
                       ('reached_late_war', 'reached the Late War'),
                       ('mean_game_seconds', 'mean game seconds')):
        if s.get(key) is not None:
            lines.append(f'- {label}: {s[key]}')
    if s.get('endings'):
        lines.append(f'- endings: {s["endings"]}')
    if s.get('bot_weights'):
        lines.append(f'- bot weights: `{s["bot_weights"]}`')

    lines += ['', '## What this does not say', '',
              'Generated by `scripts/report_note.py` from the raw report, which is',
              'under gitignored `logs/`. It records numbers only. Whether the result',
              'means the change should land is a judgement nobody made at the time',
              f'it was written ({today}), and the interval above is usually wider',
              'than the effect being looked for.', '']

    out = pathlib.Path(a.out_dir) / f'{today}-{a.slug}.md'
    out.write_text('\n'.join(lines))
    print(out)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
